### PR TITLE
Add invite feature

### PR DESCRIPTION
**Pull request by JulienBreux**

### CODE REVIEW

**Comment by JulienBreux** [comment]
@silverbucket Are-you alive? :smile:

**Comment by silverbucket** [comment]
I am :) OK, merging this now. Sorry for the delay, just had it on the back-burner.

**Comment by silverbucket** [comment]
published to npm as well

**Comment by silverbucket** [comment]
and thanks @JulienBreux ! :)

**Comment by JulienBreux** [comment]
@silverbucket Thanks lot lot lot :wink:

**Pull request merged**
